import '../app/globals.css'
import React from "react";
import localFont from 'next/font/local'

const arvo = localFont({
  src: [
    {
      path: './fonts/Arvo-Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/Arvo-Bold.ttf',
      weight: '700',
      style: 'normal'
    },
    {
      path: './fonts/Arvo-Italic.ttf',
      weight: '400',
      style: 'italic'
    },
    {
      path: './fonts/Arvo-BoldItalic.ttf',
      weight: '700',
      style: 'italic'
    }
  ],
  variable: '--font-arvo'
})

export const metadata = {
  title: "Qnurye's blog",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ch" className={`w-full min-h-screen h-full`}>
      <body className={`${arvo.className} w-full min-h-screen h-full`}>
        {children}
      </body>
    </html>
  )
}
